### ISSUE TITLE
All volumes loaded as 1

### ISSUE THREAD

**Issue by ChrisTerBeke** [thopiekar/CuraOpenSCADPlugin#4]
If the OpenSCAD file contains more that 1 volume (for example the linear extrusion example included with OpenSCAD), they are imported in Cura as a single STL file, making it impossible to place all objects on the bed.

![openscad_mutlivolume](https://user-images.githubusercontent.com/1134120/33370507-fcdece54-d4f7-11e7-8abb-5f41537ad691.png)

**Comment by thopiekar** [comment]
Agree, in the past I had inside this repository a parser for scad files. This one should then interpret variable just like thingiverse does. However, this one never worked without issues, so I removed it again. Will reimplement a own one as soon as I have the time.
Combined with #1 and the plan in the SolidWorks plugin to be able to select different files within an assembly, I want to commonize the way of listing these different configurations.
However, this is still far away since all the plugins work is currently a one-man-show.
